# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 400
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6  
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

my_arm_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
        - J1
        - J2
        - J3
        - J4
        - J5
        - J6  
      gains:
        J1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J5: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J6: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}

      constraints:
        goal_time: 0.5                   # Override default
        stopped_velocity_tolerance: 0.02 # Override default
        head_1_joint:
          trajectory: 0.05               # Not enforced if unspecified
          goal: 0.02                     # Not enforced if unspecified
        head_2_joint:
          goal: 0.01                     # Not enforced if unspecified

      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

controller_list:
  - name: my_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5  
      - J6  
    gains:
        J1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J5: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
        J6: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}