# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - J1
    - J2
    - J3
    - J4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# j1_controller:
#   type: effort_controllers/JointGroupPositionController
#   joint: J1
#   pid: {p: 10,  d: 0.1, i: 0.1}
# j2_controller:
#   type: effort_controllers/JointGroupPositionController
#   joint: J2
#   pid: {p: 10,  d: 0.1, i: 0.1}
# j3_controller:
#   type: effort_controllers/JointGroupPositionController
#   joint: J3
#   pid: {p: 10,  d: 0.1, i: 0.1}
# j4_controller:
#   type: effort_controllers/JointGroupPositionController
#   joint: J4
#   pid: {p: 10,  d: 0.1, i: 0.1}


# my_arm_controller:
#     type: effort_controllers/JointTrajectoryController
#     joints:
#       - J1
#       - J2
#       - J3
#       - J4
#     gains:
#       J1:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       J2:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       J3:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       J4:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1

controller_list:
  - name: my_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - J1
      - J2
      - J3
      - J4
    gains:
      J1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      J2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      J3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      J4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1