# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Control all joints
arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - J0
    - J1
    - J2
  
  gains:
    J0: {p: 100,  d: 10}
    J1: {p: 100,  d: 10}
    J2: {p: 100,  d: 10}

